accounts/urls.py
from django.urls import path
from .views import *

app_name = "accounts"
urlpatterns = [
    path('login/', login, name ="login"),
    path('logout/', logout, name="logout"),
    path('signup/', signup, name="signup"),
]

main/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import *
from . import views


app_name = 'main'
urlpatterns = [
    path('', mainpage, name="mainpage"),
    path('second', secondpage, name="secondpage"),
    path('new-post', new_post, name="new-post"),
    path('create', create, name="create"),
    path('<int:id>', detail, name="detail"),
    path('edit/<int:id>', edit, name="edit"),
    path('update/<int:id>', update, name="update"),
    path('delete/<int:id>', delete, name="delete"),
    path('mypage/', views.mypage, name='mypage'),
    path('tag-list', tag_list, name="tag-list"),
    path('tag-posts/<int:tag_id>', tag_posts, name="tag-posts"),

]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from main import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('accounts/', include('accounts.urls')),
    path('users/', include('users.urls')),
    path('second', views.secondpage, name="secondpage"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from .views import *

app_name = "users"
urlpatterns = [
    path('mypage/<int:id>', mypage, name="mypage"),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    age = models.TextField(max_length=3)
    bio = models.TextField(null=True, max_length=30)

main/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Tag(models.Model):
    name=models.CharField(max_length=30, null=False, blank=False)

    def __str__(self):
        return self.name
        
class Post(models.Model):
    title = models.CharField(max_length=50)
    writer = models.ForeignKey(User, null=False, blank=False, on_delete=models.CASCADE)
    content = models.TextField()
    pub_date = models.DateTimeField()
    weather = models.CharField(max_length=10)
    image = models.ImageField(upload_to="post/", blank=True, null=True)
    tags = models.ManyToManyField(Tag, related_name='posts', blank=True)
    def __str__(self):
        return self.title

    def summary(self):
        return self.content[:20]

class Comment(models.Model): 
    content = models.TextField()
    pub_date = models.DateTimeField()
    writer = models.ForeignKey(User, null=False, blank=False, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, null=False, blank=False, on_delete=models.CASCADE)
    def __str__(self):
        return self.post.title + " : " + self.content[:20] + "by" + self.writer.profile.nickname

users/models.py
from django.db import models

# Create your models here.

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib import auth
from django.contrib.auth.models import User
from .models import Profile

# Create your views here.
def login(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']

        user = auth.authenticate(request, username=username, password=password)

        if user is not None:
            auth.login(request, user)
            return redirect('main:mainpage')

        else:
            return render(request, 'accounts/login.html')

    elif request.method == "GET":
        return render(request, 'accounts/login.html')

def logout(request):
    auth.logout(request)
    return redirect('main:mainpage')

def signup(request):
    if request.method == 'POST':
        if request.POST['password'] == request.POST['confirm']:
            user = User.objects.create_user(
                username=request.POST['username'],
                password=request.POST['password']
            )
            age = request.POST['age']
            bio = request.POST['bio']

            profile = Profile(user=user, age=age, bio=bio)
            profile.save() 

            auth.login(request, user)
            return redirect('/')

    return render(request, 'accounts/signup.html')

main/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.utils import timezone
import re
from .models import *
# Create your views here.

def mainpage(request):
    context = {
        'generation': 13,
        'info': {'weather': '좋음', 'feeling': '배고픔(?)', 'note': '아기사자화이팅!'},
        'shortKeys': [
            '들여쓰기: Tab',
            '내어쓰기: Shift + Tab',
            '주석처리: 윈도우-Ctrl + /, 맥-command + /',
            '자동정렬: Shift + Alt + F or Ctrl + K + F',
            '한줄이동: Alt + 방향키(위/아래)',
            '한줄삭제: Ctrl + Shift + k or Ctrl + x',
            '같은단어전체선택: Ctrl + Shift + L'
        ]
}
    return render(request, 'main/mainpage.html', {'posts': Post})

def secondpage(request):
    posts = Post.objects.all()
    return render(request, 'main/secondpage.html', {'posts': posts})

def new_post(request):
    return render(request, 'main/new-post.html')

def detail(request, id):
    post = get_object_or_404(Post, pk=id)
    if request.method == 'GET':
        comments = Comment.objects.filter(post=post)
        return render(request, 'main/detail.html', {'post':post, 'comments': comments})
    elif request.method == 'POST':
        new_comment =Comment()
        new_comment.post = post
        new_comment.writer=request.user
        new_comment.content = request.POST['content']
        new_comment.pub_date = timezone.now() 
        new_comment.save()    
        return redirect('main:detail', id)


def edit(request, id):
    edit_post = Post.objects.get(pk=id)
    return render(request, 'main/edit.html', {"post": edit_post})

def update(request, id):
    update_post = Post.objects.get(pk=id)
    if request.user.is_authenticated and request.user == update_post.writer:
        update_post.title = request.POST['title']
        update_post.content = request.POST['content']
        update_post.pub_date = timezone.now()
        update_post.weather = request.POST['weather']
        if request.FILES.get('image'):
            update_post.image = request.FILES.get('image')
        update_post.save()
        update_post.tags.clear()
        import re
        tag_list = re.findall(r'#(\w+)', update_post.content)
        for tag_name in tag_list:
            tag, created = Tag.objects.get_or_create(name=tag_name)
            update_post.tags.add(tag)
        return redirect('main:detail', update_post.id)

def delete(request, id):
    delete_post = Post.objects.get(pk=id)
    delete_post.delete()
    return redirect('main:secondpage')

def create(request):
    if request.user.is_authenticated:
        new_post = Post()
        new_post.title = request.POST['title']
        new_post.writer = request.user
        new_post.content = request.POST['content']
        new_post.pub_date = timezone.now()
        new_post.weather = request.POST['weather']
        new_post.image = request.FILES.get('image')
        new_post.save()

        #본문을 띄어쓰기 기준으로 나누기 
        words = re.split(r'\s+', new_post.content.strip())
        tag_list = []
        # 나눈 단어가 '#'으로 시작한다면 tag_list에 저장
        for w in words:
            if len(w)>0:
                if w[0] == '#':
                    tag_list.append(w[1:]) 
        for t in tag_list:
            tag, boolean = Tag.objects.get_or_create(name=t)
            new_post.tags.add(tag.id)



        return redirect('main:detail', new_post.id)
    else:
        return redirect('accounts:login')

def mypage(request):
    user_posts = Post.objects.filter(writer=request.user)
    return render(request, 'main/mypage.html', {'user_posts': user_posts})

def tag_list(request): #모든 태그 목록을 볼 수 있는 페이지
    tags = Tag.objects.all()
    return render(request, 'main/tag-list.html', {'tags': tags})

def tag_posts(request, tag_id): #특정 태그를 가진 게시글의 목록을 볼 수 있는 페이지
    tag=get_object_or_404(Tag, id=tag_id)
    posts=tag.posts.all()
    return render(request, 'main/tag-post.html', {
    'tag' : tag,
    'posts' : posts
    })
    

users/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib import auth
from django.contrib.auth.models import User
from main.models import Post 

def mypage(request, id):
    user=get_object_or_404(User, pk=id)
    posts = Post.objects.filter(writer=user)
    context = {
        'user' :user,
        'posts': posts
    }
    return render(request, 'users/mypage.html', context)

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<form action="{% url 'accounts:login' %}" method="POST">
    {% csrf_token %}
    ID : <input type="text" name="username"><br>
    Password : <input type="password" name="password"><br>
    <input type="submit" value="로그인">
</form>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{%load static %}
{% block content %}
<form action="{% url 'accounts:signup' %}" method="POST">
    {% csrf_token %}
    <p>username</p>
    <input type="text" name="username">
    <br>
    <p>age</p>
    <input type="text" name="age">
    <br>
    <p>bio</p>
    <input type="text" name="bio">
    <br>
    <p>password</p>
    <input type="password" name="password">
    <br>
    <p>confirm</p>
    <input type="password" name="confirm">
    <br>
    <input type="submit" value="회원가입">
</form>
{% endblock %}

main/templates/main/detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h3>{{post.title}}</h3>
작성자 : {{post.writer}}
날짜 : {{post.pub_date}}
날씨 : {{post.weather}}
<P>
    {% for tag in post.tags.all %}
        <a href="{% url 'main:tag-posts' tag.id %}">#{{tag.name}}</a>
    {% endfor %}
</P>
<hr />
{% if post.image %}
<p><img src="{{post.image.url}}" alt="사진" width="100px"></p>
{% endif %}
<p>{{post.content}}</p>
{% if post.writer == user %}
<a href="{% url 'main:edit' post.id %}">글 수정하기</a>
<a href="{% url 'main:delete' post.id %}">삭제하기</a>
{% endif %}
<br>
    <div class="comment_container">
        <div class="comment_form">
            <h2></h2>
            <form action="{% url 'main:detail' post.id %}" method="POST">
                {% csrf_token %}
                댓글 쓰기 : <input type="text" name="content">
                <input type="submit" name="submit">
            </form>
        </div>
        <div class="comment_list">
            {% for comment in comments %}
            <hr>
            <h4>작성자 : {{comment.writer}}</h4>
            <p>내용 : {{comment.content}}</p>
            <p>{{comment.pub_date}}</p>
            {% endfor %}
        </div>
    </div> 
{% endblock %}

main/templates/main/edit.html
{% extends 'base.html' %} 
{% load static %} 
{% block content %} 
<h2>수정중...</h2>
<form action="{% url 'main:update' post.id %}" method="POST" enctype="multipart/form-data">
{% csrf_token %} 
<p>제목: <input type="text" name="title" value="{{post.title}}"></p>
<p>작성자: <input type="text" name="writer" value="{{post.writer}}"></p>
<p>날씨: <input type="text" name="weather" value="{{post.weather}}"></p>
{% if post.image %}
    <p><img src="{{ post.image.url }}" alt="사진" width="100px"></p>
{% endif %}
<p>사진: <input type="file" name="image"></p>
<p>내용: <textarea type="text" name="content" id="" cols="30" rows="10">{{post.content}}</textarea></p>
<button type="submit">제출</button>
</form>
{% endblock %} 

main/templates/main/mainpage.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <h1 class="contents">2025 멋쟁이사자처럼 {{generation}}기</h1>
    <div class="contents">백엔드 아기사자 조민정</div>
    <div>🦁 멋사 2주차 세션 정리 !! 🦁 </div>
    <ul>
        <li>project: 사이트 전체 의미 -> app(프로젝트를 구성하는 기능의 집합 단위)을 포함</li>
    </ul>
    <img src="{% static 'images/logi.png' %}" alt="logi" width="200px">
    <ol>
        <li>pipenv shell : 파이썬 패키지 버전 충돌 방지를 위한 가상환경 활성화</li>
        <li>초기세팅</li>
        <ul>
            <li>touch .gitignore 작성을 통해 Git에 올리지 않아도 되는 파일 제외 설정</li>
            <li>gitignore.io에서 django 검색 후 .gitignore 파일에 복붙</li>
        </ul>
    </ol>

    <div>🦁template🦁</div>
    <ol>
        <li>templates 폴더 생성 - 유저에게 제공할 파일의 구조나 레이아웃을 한 데 모아 관리 위함<br>1) main 앱 안에 templates 폴더 생성<br>2) templates 안에 main 폴더 생성<br>3) main 폴더 내 main, secondpage.html 파일 생성</li>
        <li>HTML 페이지와 view 연결 - view 작성 : 원하는 url을 통해 mainpage가 보여지게 함. (렌더링)<br>def mainpage(request):<br>   return render(request, 'main/mainpage.html')로 작성</li> 
        <li>HTML 페이지와 view 연결 - url 작성 : project > urls.py에 url에 해당하는 데이터 연결</li> 
        <li>python manage.py runserver로 페이지 확인 가능</li> 
        <li>HTML 링크 연결 : urls.py에서 지정한 name을 활용해 html 페이지에서 해당 페이지로 이동할 수 있도록 링크를 걸어줌</li> 
    </ol>
    <div>🦁template 언어🦁<br>: view에 작성된 data 가져오기, 반복문 등 기능 수행</div>
    <ol>
        <li>template 언어 : view에서 생성한 데이터는 html에서 사용 가능, for문도 활용 가능 </li>    
        <li>템플릿 필터 : 템플릿 변수를 서식에 따라 변환하는 것 </li>
        <li>템플릿 주석 : html 내용 중 주석이 필요한 경우 사용 {#주석#}<br></li>
    </ol>
    <div>🦁효율적인 코드🦁</div>
    <ol>  
        <li>템플릿 상속 : project 폴더 내, templates 폴더 생성 후 base.html 파일 생성 <br> block : 다른 파일에서 재사용 가능한 html 코드를 정의 </li>
        <li>_ 붙이는 이유 : 해당 파일이 브라우저로 호출되지 않고, 내부에서 include로 호출되거나 render로 사용된다는 의미</li>
        <li>static : 웹페이지에서 사용되는 정적인 파일을 저장하는 디렉토리 (css, image)</li>
    </ol>
    

{% endblock %}

main/templates/main/new-post.html
{% extends 'base.html' %} 
{% load static %}

{% block content %} 
<form action="{% url 'main:create' %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %} 
    <p>제목 : <input type="text" name="title"></p>
    <!-- <p>작성자 : <input type="text" name="writer"></p> -->
    <p>내용 : <textarea type="text" name="content" id="" cols="30" rows="10"></textarea></p>
    <p>사진: <input type="file" name="image"></p>
    <p>날씨 : <input type="text" name="weather"></p>
    <button type="submit">제출</button>
</form>

{% endblock %}

main/templates/main/secondpage.html
{% extends 'base.html' %}
{% block content %}

    <div>
        <div>
            {% if user.is_authenticated %}
            <a href="{% url 'main:new-post' %}">새 글 작성하기</a>
            {% endif %}
        </div>
        {% for post in posts %} 
        <div>
            <hr/>
            <h3>{{post.title}}</h3>
            {{post.writer}} | {{post.pub_date}}<br>
            {{post.summary}} 
            <a href="{% url 'main:detail' post.id %}">자세히 보기</a>
            <br>
    </div>
    {% endfor %}
    </div>
{%endblock%}

main/templates/main/tag-list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div>
    <h1>해시태그 목록</h1>
    <hr>
    {% for t in tags %}
    <div>
        <h2><a href="{% url 'main:tag-posts' t.id %}">#{{t.name}}</a></h2>
    </div>
    {% endfor %}
</div>
{% endblock %}

main/templates/main/tag-post.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div>
    <h1>#{{tag}}가 달린 게시글</h1>
    <hr>
    <div>
        {% for b in posts %}
        <hr />
        <h3>{{b.title}}</h3>
        {{b.writer}} | {{b.pub_date}}<br>
        {{b.summary}}
        <a href="{% url 'main:detail' b.id %}">자세히 보기</a>
        <br>
        {% endfor %}
    </div>
</div>
{% endblock %}

project/templates/base.html
<!DOCTYPE html>
{%load static %}
<html lang="ko">

<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" type="text/css" href="{%static 'css/project.css' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>LIKELION 13th Django Session</title>
    <style>
        a {
            text-decoration: none;
        }

        .body-container {
            background-color: #111;
            color: #fff;
            margin: 20px;
        }

        .navbar-container {
            display: flex;
            align-items: center;
            padding-left: 20px;
            gap: 40px;
            background-color: #FF9364;
            font-size: 18px;
        }

        .navbar-link {
            color: #5c3900;
            font-size: 30px;
        }

        .navbar-link:hover {
            color: #111;
        }

        .contents {
            font-size: 50px;
            margin: 20px;
        }
    </style>
</head>

<body class="body-container">
    {% include 'shared/_navbar.html' %}
    {% block content %}

    {% endblock %}
</body>

</html>

project/templates/shared/_navbar.html
<nav class="navbar-container">
    <a class="navbar-link" href="{% url 'main:mainpage' %}">DGU_likelion_13th</a>
    <a class="navbar-link" href="{% url 'main:secondpage' %}">Second Page</a>
    <a class="navbar-link" href="{% url 'main:tag-list' %}">Tag</a>
    <!--사용자 인증 정보-->
    <div class="nav-right">
        {% if user.is_authenticated %}
        <!--로그인 시 보이는 화면-->
        <ul class="nav-link-account">
            <li class="nav-link-user">{{user.username}}</li>
            <li><a href="{% url 'accounts:logout' %}">로그아웃</a></li>
            <li><a href="{% url 'users:mypage' request.user.id %}">mypage</a></li>
        </ul>
        {% else %}
        <!--로그아웃 시 보이는 화면-->
        <ul class="nav=link-account">
            <li><a href="{% url 'accounts:login' %}">로그인</a></li>
            <li><a href="{% url 'accounts:signup' %}">signup</a></li>
        </ul>
        {% endif %}
    </div>
</nav>

users/templates/users/mypage.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<h1>마이페이지에 오신 것을 환영합니다</h1>

<h3>age : {{ user.profile.age }}세</h3>
<h3>bio : {{ user.profile.bio }}</h3>

<h2>{{ user.username }}님의 글 목록</h2>

<ul>
    {% for post in posts %}
    <li>
        <h2><a href="{% url 'main:detail' post.id %}">{{ post.title }}</a></h2>
        <p>{{ post.writer }} | {{ post.pub_date }} | {{ post.weather }}</p>
        <p>{{ post.content }}</p>

        {% if post.image %}
        <p><img src="{{ post.image.url }}" alt="이미지" width="150px"></p>
        {% endif %}

        <p><a href="{% url 'main:detail' post.id %}">자세히 보기</a></p>
        <hr>
    </li>
    {% empty %}
    <li>작성한 글이 없습니다.</li>
    {% endfor %}
</ul>

{% endblock %}